# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-16 10:46
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160526_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='\u5185\u5bb9   '),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
